name = "AutoSymPTR"
uuid = "78a0c066-08f1-49a8-82f0-b29cd485e1d3"
authors = ["lxvm <lorenzo@vanmunoz.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.8"
StaticArrays = "1"
